/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { HTTPClient } from "./http.js";
import { Logger } from "./logger.js";
import { RetryConfig } from "./retries.js";
import { Params, pathToFunc } from "./url.js";

export const ServerProduction = "production";
export const ServerSandbox = "sandbox";
/**
 * Contains the list of servers available to the SDK
 */
export const ServerList = {
  [ServerProduction]: "https://api.{id}.gr4vy.app",
  [ServerSandbox]: "https://api.sandbox.{id}.gr4vy.app",
} as const;

export type SDKOptions = {
  bearerAuth?: string | (() => Promise<string>) | undefined;

  /**
   * Allows setting the merchantAccountId parameter for all supported operations
   */
  merchantAccountId?: string | undefined;

  httpClient?: HTTPClient;
  /**
   * Allows overriding the default server used by the SDK
   */
  server?: keyof typeof ServerList | undefined;
  /**
   * Sets the id variable for url substitution
   */
  id?: string | undefined;
  /**
   * Allows overriding the default server URL used by the SDK
   */
  serverURL?: string | undefined;
  /**
   * Allows overriding the default retry config used by the SDK
   */
  retryConfig?: RetryConfig;
  timeoutMs?: number;
  debugLogger?: Logger;
};

export function serverURLFromOptions(options: SDKOptions): URL | null {
  let serverURL = options.serverURL;

  const serverParams: Record<string, Params> = {
    "production": {
      "id": options.id ?? "example",
    },
    "sandbox": {
      "id": options.id ?? "example",
    },
  };

  let params: Params = {};

  if (!serverURL) {
    const server = options.server ?? ServerProduction;
    serverURL = ServerList[server] || "";
    params = serverParams[server] || {};
  }

  const u = pathToFunc(serverURL)(params);
  return new URL(u);
}

export const SDK_METADATA = {
  language: "typescript",
  openapiDocVersion: "1.0.0",
  sdkVersion: "0.18.8",
  genVersion: "2.593.3",
  userAgent: "speakeasy-sdk/typescript 0.18.8 2.593.3 1.0.0 @gr4vy/sdk",
} as const;
