/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Error403,
  Error403$inboundSchema,
  Error403$Outbound,
  Error403$outboundSchema,
} from "./error403.js";
import {
  Error403Active,
  Error403Active$inboundSchema,
  Error403Active$Outbound,
  Error403Active$outboundSchema,
} from "./error403active.js";
import {
  Error403Forbidden,
  Error403Forbidden$inboundSchema,
  Error403Forbidden$Outbound,
  Error403Forbidden$outboundSchema,
} from "./error403forbidden.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * The credentials were invalid or the caller did not have permission to act on the resource.
 */
export type CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken =
  | Error403
  | Error403Forbidden
  | Error403Active;

/** @internal */
export const CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$inboundSchema:
  z.ZodType<
    CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken,
    z.ZodTypeDef,
    unknown
  > = z.union([
    Error403$inboundSchema,
    Error403Forbidden$inboundSchema,
    Error403Active$inboundSchema,
  ]);

/** @internal */
export type CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$Outbound =
  | Error403$Outbound
  | Error403Forbidden$Outbound
  | Error403Active$Outbound;

/** @internal */
export const CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$outboundSchema:
  z.ZodType<
    CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$Outbound,
    z.ZodTypeDef,
    CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken
  > = z.union([
    Error403$outboundSchema,
    Error403Forbidden$outboundSchema,
    Error403Active$outboundSchema,
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$ {
  /** @deprecated use `CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$inboundSchema` instead. */
  export const inboundSchema =
    CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$inboundSchema;
  /** @deprecated use `CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$outboundSchema` instead. */
  export const outboundSchema =
    CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$outboundSchema;
  /** @deprecated use `CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$Outbound` instead. */
  export type Outbound =
    CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$Outbound;
}

export function createPaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkTokenToJSON(
  createPaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken:
    CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken,
): string {
  return JSON.stringify(
    CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$outboundSchema
      .parse(
        createPaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken,
      ),
  );
}

export function createPaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkTokenFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentMethodNetworkTokenResponse403CreatePaymentMethodNetworkToken' from JSON`,
  );
}
