/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Error403,
  Error403$inboundSchema,
  Error403$Outbound,
  Error403$outboundSchema,
} from "./error403.js";
import {
  Error403Active,
  Error403Active$inboundSchema,
  Error403Active$Outbound,
  Error403Active$outboundSchema,
} from "./error403active.js";
import {
  Error403Forbidden,
  Error403Forbidden$inboundSchema,
  Error403Forbidden$Outbound,
  Error403Forbidden$outboundSchema,
} from "./error403forbidden.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * The credentials were invalid or the caller did not have permission to act on the resource.
 */
export type CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession =
  | Error403
  | Error403Forbidden
  | Error403Active;

/** @internal */
export const CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$inboundSchema:
  z.ZodType<
    CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession,
    z.ZodTypeDef,
    unknown
  > = z.union([
    Error403$inboundSchema,
    Error403Forbidden$inboundSchema,
    Error403Active$inboundSchema,
  ]);

/** @internal */
export type CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$Outbound =
  | Error403$Outbound
  | Error403Forbidden$Outbound
  | Error403Active$Outbound;

/** @internal */
export const CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$outboundSchema:
  z.ZodType<
    CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$Outbound,
    z.ZodTypeDef,
    CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession
  > = z.union([
    Error403$outboundSchema,
    Error403Forbidden$outboundSchema,
    Error403Active$outboundSchema,
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$ {
  /** @deprecated use `CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$inboundSchema` instead. */
  export const inboundSchema =
    CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$inboundSchema;
  /** @deprecated use `CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$outboundSchema` instead. */
  export const outboundSchema =
    CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$outboundSchema;
  /** @deprecated use `CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$Outbound` instead. */
  export type Outbound =
    CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$Outbound;
}

export function createPaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSessionToJSON(
  createPaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession:
    CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession,
): string {
  return JSON.stringify(
    CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$outboundSchema
      .parse(
        createPaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession,
      ),
  );
}

export function createPaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSessionFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentServiceDefinitionSessionResponse403CreatePaymentServiceDefinitionSession' from JSON`,
  );
}
