/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Error403,
  Error403$inboundSchema,
  Error403$Outbound,
  Error403$outboundSchema,
} from "./error403.js";
import {
  Error403Active,
  Error403Active$inboundSchema,
  Error403Active$Outbound,
  Error403Active$outboundSchema,
} from "./error403active.js";
import {
  Error403Forbidden,
  Error403Forbidden$inboundSchema,
  Error403Forbidden$Outbound,
  Error403Forbidden$outboundSchema,
} from "./error403forbidden.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * The credentials were invalid or the caller did not have permission to act on the resource.
 */
export type CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram =
  | Error403
  | Error403Forbidden
  | Error403Active;

/** @internal */
export const CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$inboundSchema:
  z.ZodType<
    CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram,
    z.ZodTypeDef,
    unknown
  > = z.union([
    Error403$inboundSchema,
    Error403Forbidden$inboundSchema,
    Error403Active$inboundSchema,
  ]);

/** @internal */
export type CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$Outbound =
  | Error403$Outbound
  | Error403Forbidden$Outbound
  | Error403Active$Outbound;

/** @internal */
export const CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$outboundSchema:
  z.ZodType<
    CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$Outbound,
    z.ZodTypeDef,
    CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram
  > = z.union([
    Error403$outboundSchema,
    Error403Forbidden$outboundSchema,
    Error403Active$outboundSchema,
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$ {
  /** @deprecated use `CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$inboundSchema` instead. */
  export const inboundSchema =
    CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$inboundSchema;
  /** @deprecated use `CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$outboundSchema` instead. */
  export const outboundSchema =
    CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$outboundSchema;
  /** @deprecated use `CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$Outbound` instead. */
  export type Outbound =
    CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$Outbound;
}

export function createPaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogramToJSON(
  createPaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram:
    CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram,
): string {
  return JSON.stringify(
    CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$outboundSchema
      .parse(
        createPaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram,
      ),
  );
}

export function createPaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogramFromJSON(
  jsonString: string,
): SafeParseResult<
  CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentMethodNetworkTokenCryptogramResponse403CreatePaymentMethodNetworkTokenCryptogram' from JSON`,
  );
}
