/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Error403,
  Error403$inboundSchema,
  Error403$Outbound,
  Error403$outboundSchema,
} from "./error403.js";
import {
  Error403Active,
  Error403Active$inboundSchema,
  Error403Active$Outbound,
  Error403Active$outboundSchema,
} from "./error403active.js";
import {
  Error403Forbidden,
  Error403Forbidden$inboundSchema,
  Error403Forbidden$Outbound,
  Error403Forbidden$outboundSchema,
} from "./error403forbidden.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * The credentials were invalid or the caller did not have permission to act on the resource.
 */
export type CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession =
  | Error403
  | Error403Forbidden
  | Error403Active;

/** @internal */
export const CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$inboundSchema:
  z.ZodType<
    CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession,
    z.ZodTypeDef,
    unknown
  > = z.union([
    Error403$inboundSchema,
    Error403Forbidden$inboundSchema,
    Error403Active$inboundSchema,
  ]);

/** @internal */
export type CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$Outbound =
  | Error403$Outbound
  | Error403Forbidden$Outbound
  | Error403Active$Outbound;

/** @internal */
export const CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$outboundSchema:
  z.ZodType<
    CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$Outbound,
    z.ZodTypeDef,
    CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession
  > = z.union([
    Error403$outboundSchema,
    Error403Forbidden$outboundSchema,
    Error403Active$outboundSchema,
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$ {
  /** @deprecated use `CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$inboundSchema` instead. */
  export const inboundSchema =
    CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$inboundSchema;
  /** @deprecated use `CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$outboundSchema` instead. */
  export const outboundSchema =
    CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$outboundSchema;
  /** @deprecated use `CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$Outbound` instead. */
  export type Outbound =
    CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$Outbound;
}

export function createApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSessionToJSON(
  createApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession:
    CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession,
): string {
  return JSON.stringify(
    CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$outboundSchema
      .parse(
        createApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession,
      ),
  );
}

export function createApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSessionFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreateApplePayDigitalWalletSessionResponse403CreateApplePayDigitalWalletSession' from JSON`,
  );
}
