/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Error403,
  Error403$inboundSchema,
  Error403$Outbound,
  Error403$outboundSchema,
} from "./error403.js";
import {
  Error403Active,
  Error403Active$inboundSchema,
  Error403Active$Outbound,
  Error403Active$outboundSchema,
} from "./error403active.js";
import {
  Error403Forbidden,
  Error403Forbidden$inboundSchema,
  Error403Forbidden$Outbound,
  Error403Forbidden$outboundSchema,
} from "./error403forbidden.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * The credentials were invalid or the caller did not have permission to act on the resource.
 */
export type GetTransactionSummaryResponse403GetTransactionSummary =
  | Error403
  | Error403Forbidden
  | Error403Active;

/** @internal */
export const GetTransactionSummaryResponse403GetTransactionSummary$inboundSchema:
  z.ZodType<
    GetTransactionSummaryResponse403GetTransactionSummary,
    z.ZodTypeDef,
    unknown
  > = z.union([
    Error403$inboundSchema,
    Error403Forbidden$inboundSchema,
    Error403Active$inboundSchema,
  ]);

/** @internal */
export type GetTransactionSummaryResponse403GetTransactionSummary$Outbound =
  | Error403$Outbound
  | Error403Forbidden$Outbound
  | Error403Active$Outbound;

/** @internal */
export const GetTransactionSummaryResponse403GetTransactionSummary$outboundSchema:
  z.ZodType<
    GetTransactionSummaryResponse403GetTransactionSummary$Outbound,
    z.ZodTypeDef,
    GetTransactionSummaryResponse403GetTransactionSummary
  > = z.union([
    Error403$outboundSchema,
    Error403Forbidden$outboundSchema,
    Error403Active$outboundSchema,
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetTransactionSummaryResponse403GetTransactionSummary$ {
  /** @deprecated use `GetTransactionSummaryResponse403GetTransactionSummary$inboundSchema` instead. */
  export const inboundSchema =
    GetTransactionSummaryResponse403GetTransactionSummary$inboundSchema;
  /** @deprecated use `GetTransactionSummaryResponse403GetTransactionSummary$outboundSchema` instead. */
  export const outboundSchema =
    GetTransactionSummaryResponse403GetTransactionSummary$outboundSchema;
  /** @deprecated use `GetTransactionSummaryResponse403GetTransactionSummary$Outbound` instead. */
  export type Outbound =
    GetTransactionSummaryResponse403GetTransactionSummary$Outbound;
}

export function getTransactionSummaryResponse403GetTransactionSummaryToJSON(
  getTransactionSummaryResponse403GetTransactionSummary:
    GetTransactionSummaryResponse403GetTransactionSummary,
): string {
  return JSON.stringify(
    GetTransactionSummaryResponse403GetTransactionSummary$outboundSchema.parse(
      getTransactionSummaryResponse403GetTransactionSummary,
    ),
  );
}

export function getTransactionSummaryResponse403GetTransactionSummaryFromJSON(
  jsonString: string,
): SafeParseResult<
  GetTransactionSummaryResponse403GetTransactionSummary,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetTransactionSummaryResponse403GetTransactionSummary$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetTransactionSummaryResponse403GetTransactionSummary' from JSON`,
  );
}
