/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  Error403,
  Error403$inboundSchema,
  Error403$Outbound,
  Error403$outboundSchema,
} from "./error403.js";
import {
  Error403Active,
  Error403Active$inboundSchema,
  Error403Active$Outbound,
  Error403Active$outboundSchema,
} from "./error403active.js";
import {
  Error403Forbidden,
  Error403Forbidden$inboundSchema,
  Error403Forbidden$Outbound,
  Error403Forbidden$outboundSchema,
} from "./error403forbidden.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * The credentials were invalid or the caller did not have permission to act on the resource.
 */
export type ListBuyerGiftCardsResponse403ListBuyerGiftCards =
  | Error403
  | Error403Forbidden
  | Error403Active;

/** @internal */
export const ListBuyerGiftCardsResponse403ListBuyerGiftCards$inboundSchema:
  z.ZodType<
    ListBuyerGiftCardsResponse403ListBuyerGiftCards,
    z.ZodTypeDef,
    unknown
  > = z.union([
    Error403$inboundSchema,
    Error403Forbidden$inboundSchema,
    Error403Active$inboundSchema,
  ]);

/** @internal */
export type ListBuyerGiftCardsResponse403ListBuyerGiftCards$Outbound =
  | Error403$Outbound
  | Error403Forbidden$Outbound
  | Error403Active$Outbound;

/** @internal */
export const ListBuyerGiftCardsResponse403ListBuyerGiftCards$outboundSchema:
  z.ZodType<
    ListBuyerGiftCardsResponse403ListBuyerGiftCards$Outbound,
    z.ZodTypeDef,
    ListBuyerGiftCardsResponse403ListBuyerGiftCards
  > = z.union([
    Error403$outboundSchema,
    Error403Forbidden$outboundSchema,
    Error403Active$outboundSchema,
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListBuyerGiftCardsResponse403ListBuyerGiftCards$ {
  /** @deprecated use `ListBuyerGiftCardsResponse403ListBuyerGiftCards$inboundSchema` instead. */
  export const inboundSchema =
    ListBuyerGiftCardsResponse403ListBuyerGiftCards$inboundSchema;
  /** @deprecated use `ListBuyerGiftCardsResponse403ListBuyerGiftCards$outboundSchema` instead. */
  export const outboundSchema =
    ListBuyerGiftCardsResponse403ListBuyerGiftCards$outboundSchema;
  /** @deprecated use `ListBuyerGiftCardsResponse403ListBuyerGiftCards$Outbound` instead. */
  export type Outbound =
    ListBuyerGiftCardsResponse403ListBuyerGiftCards$Outbound;
}

export function listBuyerGiftCardsResponse403ListBuyerGiftCardsToJSON(
  listBuyerGiftCardsResponse403ListBuyerGiftCards:
    ListBuyerGiftCardsResponse403ListBuyerGiftCards,
): string {
  return JSON.stringify(
    ListBuyerGiftCardsResponse403ListBuyerGiftCards$outboundSchema.parse(
      listBuyerGiftCardsResponse403ListBuyerGiftCards,
    ),
  );
}

export function listBuyerGiftCardsResponse403ListBuyerGiftCardsFromJSON(
  jsonString: string,
): SafeParseResult<
  ListBuyerGiftCardsResponse403ListBuyerGiftCards,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListBuyerGiftCardsResponse403ListBuyerGiftCards$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListBuyerGiftCardsResponse403ListBuyerGiftCards' from JSON`,
  );
}
