/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { buyersCreate } from "../../funcs/buyersCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  buyerCreate: components.BuyerCreate$inboundSchema,
  timeoutInSeconds: z.number().default(1),
  merchantAccountId: z.nullable(z.string()).optional(),
};

export const tool$buyersCreate: ToolDefinition<typeof args> = {
  name: "buyers-create",
  description: `Add a buyer

Create a new buyer record.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await buyersCreate(
      client,
      args.buyerCreate,
      args.timeoutInSeconds,
      args.merchantAccountId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
