/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { paymentServicesUpdate } from "../../funcs/paymentServicesUpdate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  paymentServiceUpdate: components.PaymentServiceUpdate$inboundSchema,
  paymentServiceId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
};

export const tool$paymentServicesUpdate: ToolDefinition<typeof args> = {
  name: "payment-services-update",
  description: `Configure a payment service

Configures a new payment service for use by merchants.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await paymentServicesUpdate(
      client,
      args.paymentServiceUpdate,
      args.paymentServiceId,
      args.merchantAccountId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
