/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { paymentMethodsNetworkTokensSuspend } from "../../funcs/paymentMethodsNetworkTokensSuspend.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  paymentMethodId: z.string(),
  networkTokenId: z.string(),
  applicationName: z.string().default("core-api"),
  merchantAccountId: z.nullable(z.string()).optional(),
};

export const tool$paymentMethodsNetworkTokensSuspend: ToolDefinition<
  typeof args
> = {
  name: "payment-methods-network-tokens-suspend",
  description: `Suspend network token

Suspend a network token for a payment method.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await paymentMethodsNetworkTokensSuspend(
      client,
      args.paymentMethodId,
      args.networkTokenId,
      args.applicationName,
      args.merchantAccountId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
