/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { payoutsList } from "../../funcs/payoutsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  xGr4vyMerchantAccountId: z.nullable(z.string()).optional(),
};

export const tool$payoutsList: ToolDefinition<typeof args> = {
  name: "payouts-list",
  description: `List payouts created.

Returns a list of payouts made.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await payoutsList(
      client,
      args.cursor,
      args.limit,
      args.xGr4vyMerchantAccountId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
