/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { transactionsRefundsList } from "../../funcs/transactionsRefundsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  transactionId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
};

export const tool$transactionsRefundsList: ToolDefinition<typeof args> = {
  name: "transactions-refunds-list",
  description: `List transaction refunds

List refunds for a transaction.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionsRefundsList(
      client,
      args.transactionId,
      args.merchantAccountId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
