/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reportExecutionsList } from "../funcs/reportExecutionsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class ReportExecutions extends ClientSDK {
  /**
   * List executed reports
   *
   * @remarks
   * List all executed reports that have been generated.
   */
  async list(
    request?: operations.ListAllReportExecutionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListAllReportExecutionsResponse, { cursor: string }>
  > {
    return unwrapResultIterator(reportExecutionsList(
      this,
      request,
      options,
    ));
  }
}
