/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { AccountUpdater } from "./accountupdater.js";
import { AuditLogs } from "./auditlogs.js";
import { Buyers } from "./buyers.js";
import { CardSchemeDefinitions } from "./cardschemedefinitions.js";
import { CheckoutSessions } from "./checkoutsessions.js";
import { DigitalWallets } from "./digitalwallets.js";
import { GiftCards } from "./giftcards.js";
import { MerchantAccounts } from "./merchantaccounts.js";
import { PaymentMethods } from "./paymentmethods.js";
import { PaymentOptions } from "./paymentoptions.js";
import { Payouts } from "./payouts.js";
import { Refunds } from "./refunds.js";
import { Transaction } from "./transaction.js";
import { Transactions } from "./transactions.js";

export class Gr4vy extends ClientSDK {
  private _accountUpdater?: AccountUpdater;
  get accountUpdater(): AccountUpdater {
    return (this._accountUpdater ??= new AccountUpdater(this._options));
  }

  private _buyers?: Buyers;
  get buyers(): Buyers {
    return (this._buyers ??= new Buyers(this._options));
  }

  private _paymentMethods?: PaymentMethods;
  get paymentMethods(): PaymentMethods {
    return (this._paymentMethods ??= new PaymentMethods(this._options));
  }

  private _giftCards?: GiftCards;
  get giftCards(): GiftCards {
    return (this._giftCards ??= new GiftCards(this._options));
  }

  private _cardSchemeDefinitions?: CardSchemeDefinitions;
  get cardSchemeDefinitions(): CardSchemeDefinitions {
    return (this._cardSchemeDefinitions ??= new CardSchemeDefinitions(
      this._options,
    ));
  }

  private _digitalWallets?: DigitalWallets;
  get digitalWallets(): DigitalWallets {
    return (this._digitalWallets ??= new DigitalWallets(this._options));
  }

  private _transactions?: Transactions;
  get transactions(): Transactions {
    return (this._transactions ??= new Transactions(this._options));
  }

  private _transaction?: Transaction;
  get transaction(): Transaction {
    return (this._transaction ??= new Transaction(this._options));
  }

  private _refunds?: Refunds;
  get refunds(): Refunds {
    return (this._refunds ??= new Refunds(this._options));
  }

  private _paymentOptions?: PaymentOptions;
  get paymentOptions(): PaymentOptions {
    return (this._paymentOptions ??= new PaymentOptions(this._options));
  }

  private _auditLogs?: AuditLogs;
  get auditLogs(): AuditLogs {
    return (this._auditLogs ??= new AuditLogs(this._options));
  }

  private _checkoutSessions?: CheckoutSessions;
  get checkoutSessions(): CheckoutSessions {
    return (this._checkoutSessions ??= new CheckoutSessions(this._options));
  }

  private _merchantAccounts?: MerchantAccounts;
  get merchantAccounts(): MerchantAccounts {
    return (this._merchantAccounts ??= new MerchantAccounts(this._options));
  }

  private _payouts?: Payouts;
  get payouts(): Payouts {
    return (this._payouts ??= new Payouts(this._options));
  }
}
