/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @gr4vy/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx browsePaymentMethodDefinitionsGet.ts
 */

import { Gr4vy } from "@gr4vy/sdk";

const gr4vy = new Gr4vy({
  merchantAccountId: "<id>",
  bearerAuth: process.env["GR4VY_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await gr4vy.browsePaymentMethodDefinitionsGet();

  console.log(result);
}

main().catch(console.error);
