/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type AddDigitalWalletDomainNameRequest = {
    /**
     * The ID of the registered digital wallet.
     */
    digitalWalletId: string;
    digitalWalletDomain?: components.DigitalWalletDomain | undefined;
};

/** @internal */
export const AddDigitalWalletDomainNameRequest$inboundSchema: z.ZodType<
    AddDigitalWalletDomainNameRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        digital_wallet_id: z.string(),
        DigitalWalletDomain: components.DigitalWalletDomain$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            digital_wallet_id: "digitalWalletId",
            DigitalWalletDomain: "digitalWalletDomain",
        });
    });

/** @internal */
export type AddDigitalWalletDomainNameRequest$Outbound = {
    digital_wallet_id: string;
    DigitalWalletDomain?: components.DigitalWalletDomain$Outbound | undefined;
};

/** @internal */
export const AddDigitalWalletDomainNameRequest$outboundSchema: z.ZodType<
    AddDigitalWalletDomainNameRequest$Outbound,
    z.ZodTypeDef,
    AddDigitalWalletDomainNameRequest
> = z
    .object({
        digitalWalletId: z.string(),
        digitalWalletDomain: components.DigitalWalletDomain$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            digitalWalletId: "digital_wallet_id",
            digitalWalletDomain: "DigitalWalletDomain",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddDigitalWalletDomainNameRequest$ {
    /** @deprecated use `AddDigitalWalletDomainNameRequest$inboundSchema` instead. */
    export const inboundSchema = AddDigitalWalletDomainNameRequest$inboundSchema;
    /** @deprecated use `AddDigitalWalletDomainNameRequest$outboundSchema` instead. */
    export const outboundSchema = AddDigitalWalletDomainNameRequest$outboundSchema;
    /** @deprecated use `AddDigitalWalletDomainNameRequest$Outbound` instead. */
    export type Outbound = AddDigitalWalletDomainNameRequest$Outbound;
}
