/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CaptureTransactionRequest = {
    transactionId: string;
    transactionCapture: components.TransactionCapture;
};

/** @internal */
export const CaptureTransactionRequest$inboundSchema: z.ZodType<
    CaptureTransactionRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        transaction_id: z.string(),
        TransactionCapture: components.TransactionCapture$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            transaction_id: "transactionId",
            TransactionCapture: "transactionCapture",
        });
    });

/** @internal */
export type CaptureTransactionRequest$Outbound = {
    transaction_id: string;
    TransactionCapture: components.TransactionCapture$Outbound;
};

/** @internal */
export const CaptureTransactionRequest$outboundSchema: z.ZodType<
    CaptureTransactionRequest$Outbound,
    z.ZodTypeDef,
    CaptureTransactionRequest
> = z
    .object({
        transactionId: z.string(),
        transactionCapture: components.TransactionCapture$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            transactionId: "transaction_id",
            transactionCapture: "TransactionCapture",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CaptureTransactionRequest$ {
    /** @deprecated use `CaptureTransactionRequest$inboundSchema` instead. */
    export const inboundSchema = CaptureTransactionRequest$inboundSchema;
    /** @deprecated use `CaptureTransactionRequest$outboundSchema` instead. */
    export const outboundSchema = CaptureTransactionRequest$outboundSchema;
    /** @deprecated use `CaptureTransactionRequest$Outbound` instead. */
    export type Outbound = CaptureTransactionRequest$Outbound;
}
