/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreatePaymentMethodNetworkTokenRequest = {
  /**
   * The ID of the payment method
   */
  paymentMethodId: string;
  timeoutInSeconds?: number | undefined;
  networkTokenCreate: components.NetworkTokenCreate;
};

/** @internal */
export const CreatePaymentMethodNetworkTokenRequest$inboundSchema: z.ZodType<
  CreatePaymentMethodNetworkTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  payment_method_id: z.string(),
  timeout_in_seconds: z.number().default(1),
  NetworkTokenCreate: components.NetworkTokenCreate$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "payment_method_id": "paymentMethodId",
    "timeout_in_seconds": "timeoutInSeconds",
    "NetworkTokenCreate": "networkTokenCreate",
  });
});

/** @internal */
export type CreatePaymentMethodNetworkTokenRequest$Outbound = {
  payment_method_id: string;
  timeout_in_seconds: number;
  NetworkTokenCreate: components.NetworkTokenCreate$Outbound;
};

/** @internal */
export const CreatePaymentMethodNetworkTokenRequest$outboundSchema: z.ZodType<
  CreatePaymentMethodNetworkTokenRequest$Outbound,
  z.ZodTypeDef,
  CreatePaymentMethodNetworkTokenRequest
> = z.object({
  paymentMethodId: z.string(),
  timeoutInSeconds: z.number().default(1),
  networkTokenCreate: components.NetworkTokenCreate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    paymentMethodId: "payment_method_id",
    timeoutInSeconds: "timeout_in_seconds",
    networkTokenCreate: "NetworkTokenCreate",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePaymentMethodNetworkTokenRequest$ {
  /** @deprecated use `CreatePaymentMethodNetworkTokenRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreatePaymentMethodNetworkTokenRequest$inboundSchema;
  /** @deprecated use `CreatePaymentMethodNetworkTokenRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreatePaymentMethodNetworkTokenRequest$outboundSchema;
  /** @deprecated use `CreatePaymentMethodNetworkTokenRequest$Outbound` instead. */
  export type Outbound = CreatePaymentMethodNetworkTokenRequest$Outbound;
}

export function createPaymentMethodNetworkTokenRequestToJSON(
  createPaymentMethodNetworkTokenRequest:
    CreatePaymentMethodNetworkTokenRequest,
): string {
  return JSON.stringify(
    CreatePaymentMethodNetworkTokenRequest$outboundSchema.parse(
      createPaymentMethodNetworkTokenRequest,
    ),
  );
}

export function createPaymentMethodNetworkTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentMethodNetworkTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreatePaymentMethodNetworkTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentMethodNetworkTokenRequest' from JSON`,
  );
}
