/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeletePaymentServiceTokenRequest = {
    paymentMethodId: string;
    paymentServiceTokenId: string;
};

/** @internal */
export const DeletePaymentServiceTokenRequest$inboundSchema: z.ZodType<
    DeletePaymentServiceTokenRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        payment_method_id: z.string(),
        payment_service_token_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            payment_method_id: "paymentMethodId",
            payment_service_token_id: "paymentServiceTokenId",
        });
    });

/** @internal */
export type DeletePaymentServiceTokenRequest$Outbound = {
    payment_method_id: string;
    payment_service_token_id: string;
};

/** @internal */
export const DeletePaymentServiceTokenRequest$outboundSchema: z.ZodType<
    DeletePaymentServiceTokenRequest$Outbound,
    z.ZodTypeDef,
    DeletePaymentServiceTokenRequest
> = z
    .object({
        paymentMethodId: z.string(),
        paymentServiceTokenId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            paymentMethodId: "payment_method_id",
            paymentServiceTokenId: "payment_service_token_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeletePaymentServiceTokenRequest$ {
    /** @deprecated use `DeletePaymentServiceTokenRequest$inboundSchema` instead. */
    export const inboundSchema = DeletePaymentServiceTokenRequest$inboundSchema;
    /** @deprecated use `DeletePaymentServiceTokenRequest$outboundSchema` instead. */
    export const outboundSchema = DeletePaymentServiceTokenRequest$outboundSchema;
    /** @deprecated use `DeletePaymentServiceTokenRequest$Outbound` instead. */
    export type Outbound = DeletePaymentServiceTokenRequest$Outbound;
}
