/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetAntiFraudServiceRequest = {
    /**
     * The unique ID for an anti-fraud service.
     */
    antiFraudServiceId: string;
};

/** @internal */
export const GetAntiFraudServiceRequest$inboundSchema: z.ZodType<
    GetAntiFraudServiceRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        anti_fraud_service_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            anti_fraud_service_id: "antiFraudServiceId",
        });
    });

/** @internal */
export type GetAntiFraudServiceRequest$Outbound = {
    anti_fraud_service_id: string;
};

/** @internal */
export const GetAntiFraudServiceRequest$outboundSchema: z.ZodType<
    GetAntiFraudServiceRequest$Outbound,
    z.ZodTypeDef,
    GetAntiFraudServiceRequest
> = z
    .object({
        antiFraudServiceId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            antiFraudServiceId: "anti_fraud_service_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAntiFraudServiceRequest$ {
    /** @deprecated use `GetAntiFraudServiceRequest$inboundSchema` instead. */
    export const inboundSchema = GetAntiFraudServiceRequest$inboundSchema;
    /** @deprecated use `GetAntiFraudServiceRequest$outboundSchema` instead. */
    export const outboundSchema = GetAntiFraudServiceRequest$outboundSchema;
    /** @deprecated use `GetAntiFraudServiceRequest$Outbound` instead. */
    export type Outbound = GetAntiFraudServiceRequest$Outbound;
}
