/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetBuyerBillingDetailsRequest = {
    /**
     * Filters the results to only the items for which the `buyer` has an
     *
     * @remarks
     * `id` that matches this value.
     */
    buyerId?: string | undefined;
    /**
     * Filters the results to only the items for which the `buyer` has an
     *
     * @remarks
     * `external_identifier` that matches this value.
     */
    buyerExternalIdentifier?: string | undefined;
};

/** @internal */
export const GetBuyerBillingDetailsRequest$inboundSchema: z.ZodType<
    GetBuyerBillingDetailsRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        buyer_id: z.string().optional(),
        buyer_external_identifier: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            buyer_id: "buyerId",
            buyer_external_identifier: "buyerExternalIdentifier",
        });
    });

/** @internal */
export type GetBuyerBillingDetailsRequest$Outbound = {
    buyer_id?: string | undefined;
    buyer_external_identifier?: string | undefined;
};

/** @internal */
export const GetBuyerBillingDetailsRequest$outboundSchema: z.ZodType<
    GetBuyerBillingDetailsRequest$Outbound,
    z.ZodTypeDef,
    GetBuyerBillingDetailsRequest
> = z
    .object({
        buyerId: z.string().optional(),
        buyerExternalIdentifier: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            buyerId: "buyer_id",
            buyerExternalIdentifier: "buyer_external_identifier",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBuyerBillingDetailsRequest$ {
    /** @deprecated use `GetBuyerBillingDetailsRequest$inboundSchema` instead. */
    export const inboundSchema = GetBuyerBillingDetailsRequest$inboundSchema;
    /** @deprecated use `GetBuyerBillingDetailsRequest$outboundSchema` instead. */
    export const outboundSchema = GetBuyerBillingDetailsRequest$outboundSchema;
    /** @deprecated use `GetBuyerBillingDetailsRequest$Outbound` instead. */
    export type Outbound = GetBuyerBillingDetailsRequest$Outbound;
}
