/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetCheckoutSessionRequest = {
    sessionId: string;
};

/** @internal */
export const GetCheckoutSessionRequest$inboundSchema: z.ZodType<
    GetCheckoutSessionRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        session_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            session_id: "sessionId",
        });
    });

/** @internal */
export type GetCheckoutSessionRequest$Outbound = {
    session_id: string;
};

/** @internal */
export const GetCheckoutSessionRequest$outboundSchema: z.ZodType<
    GetCheckoutSessionRequest$Outbound,
    z.ZodTypeDef,
    GetCheckoutSessionRequest
> = z
    .object({
        sessionId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            sessionId: "session_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCheckoutSessionRequest$ {
    /** @deprecated use `GetCheckoutSessionRequest$inboundSchema` instead. */
    export const inboundSchema = GetCheckoutSessionRequest$inboundSchema;
    /** @deprecated use `GetCheckoutSessionRequest$outboundSchema` instead. */
    export const outboundSchema = GetCheckoutSessionRequest$outboundSchema;
    /** @deprecated use `GetCheckoutSessionRequest$Outbound` instead. */
    export type Outbound = GetCheckoutSessionRequest$Outbound;
}
