/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetCheckoutSessionRequest = {
    /**
     * The unique ID for a Checkout Session.
     */
    checkoutSessionId: string;
};

export type GetCheckoutSessionResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Returns details about a current Checkout Session.
     */
    checkoutSession?: components.CheckoutSession | undefined;
    /**
     * Returns a generic error.
     */
    errorGeneric?: components.ErrorGeneric | undefined;
};

/** @internal */
export namespace GetCheckoutSessionRequest$ {
    export type Inbound = {
        checkout_session_id: string;
    };

    export const inboundSchema: z.ZodType<GetCheckoutSessionRequest, z.ZodTypeDef, Inbound> = z
        .object({
            checkout_session_id: z.string(),
        })
        .transform((v) => {
            return {
                checkoutSessionId: v.checkout_session_id,
            };
        });

    export type Outbound = {
        checkout_session_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetCheckoutSessionRequest> = z
        .object({
            checkoutSessionId: z.string(),
        })
        .transform((v) => {
            return {
                checkout_session_id: v.checkoutSessionId,
            };
        });
}

/** @internal */
export namespace GetCheckoutSessionResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        CheckoutSession?: components.CheckoutSession$.Inbound | undefined;
        ErrorGeneric?: components.ErrorGeneric$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetCheckoutSessionResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            CheckoutSession: components.CheckoutSession$.inboundSchema.optional(),
            ErrorGeneric: components.ErrorGeneric$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.CheckoutSession === undefined
                    ? null
                    : { checkoutSession: v.CheckoutSession }),
                ...(v.ErrorGeneric === undefined ? null : { errorGeneric: v.ErrorGeneric }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        CheckoutSession?: components.CheckoutSession$.Outbound | undefined;
        ErrorGeneric?: components.ErrorGeneric$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetCheckoutSessionResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            checkoutSession: components.CheckoutSession$.outboundSchema.optional(),
            errorGeneric: components.ErrorGeneric$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.checkoutSession === undefined
                    ? null
                    : { CheckoutSession: v.checkoutSession }),
                ...(v.errorGeneric === undefined ? null : { ErrorGeneric: v.errorGeneric }),
            };
        });
}
