/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetDigitalWalletRequest = {
    /**
     * The ID of the registered digital wallet.
     */
    digitalWalletId: string;
};

export type GetDigitalWalletResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Returns a registered digital wallet.
     */
    digitalWallet?: components.DigitalWallet | undefined;
};

/** @internal */
export namespace GetDigitalWalletRequest$ {
    export type Inbound = {
        digital_wallet_id: string;
    };

    export const inboundSchema: z.ZodType<GetDigitalWalletRequest, z.ZodTypeDef, Inbound> = z
        .object({
            digital_wallet_id: z.string(),
        })
        .transform((v) => {
            return {
                digitalWalletId: v.digital_wallet_id,
            };
        });

    export type Outbound = {
        digital_wallet_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDigitalWalletRequest> = z
        .object({
            digitalWalletId: z.string(),
        })
        .transform((v) => {
            return {
                digital_wallet_id: v.digitalWalletId,
            };
        });
}

/** @internal */
export namespace GetDigitalWalletResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        DigitalWallet?: components.DigitalWallet$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<GetDigitalWalletResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            DigitalWallet: components.DigitalWallet$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.DigitalWallet === undefined ? null : { digitalWallet: v.DigitalWallet }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        DigitalWallet?: components.DigitalWallet$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetDigitalWalletResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            digitalWallet: components.DigitalWallet$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.digitalWallet === undefined ? null : { DigitalWallet: v.digitalWallet }),
            };
        });
}
