/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetGiftCardServiceDefinitionRequest = {
    /**
     * The unique ID of the gift card service definition.
     */
    giftCardServiceDefinitionId: string;
};

export type GetGiftCardServiceDefinitionResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Returns a gift card service definition.
     */
    giftCardServiceDefinition?: components.GiftCardServiceDefinition | undefined;
};

/** @internal */
export namespace GetGiftCardServiceDefinitionRequest$ {
    export type Inbound = {
        gift_card_service_definition_id: string;
    };

    export const inboundSchema: z.ZodType<
        GetGiftCardServiceDefinitionRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            gift_card_service_definition_id: z.string(),
        })
        .transform((v) => {
            return {
                giftCardServiceDefinitionId: v.gift_card_service_definition_id,
            };
        });

    export type Outbound = {
        gift_card_service_definition_id: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetGiftCardServiceDefinitionRequest
    > = z
        .object({
            giftCardServiceDefinitionId: z.string(),
        })
        .transform((v) => {
            return {
                gift_card_service_definition_id: v.giftCardServiceDefinitionId,
            };
        });
}

/** @internal */
export namespace GetGiftCardServiceDefinitionResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        GiftCardServiceDefinition?: components.GiftCardServiceDefinition$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        GetGiftCardServiceDefinitionResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            GiftCardServiceDefinition:
                components.GiftCardServiceDefinition$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.GiftCardServiceDefinition === undefined
                    ? null
                    : { giftCardServiceDefinition: v.GiftCardServiceDefinition }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        GiftCardServiceDefinition?: components.GiftCardServiceDefinition$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetGiftCardServiceDefinitionResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            giftCardServiceDefinition:
                components.GiftCardServiceDefinition$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.giftCardServiceDefinition === undefined
                    ? null
                    : { GiftCardServiceDefinition: v.giftCardServiceDefinition }),
            };
        });
}
