/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListCardSchemeDefinitionsRequest = {
  /**
   * The ID of the merchant account to use for this request.
   */
  xGr4vyMerchantAccountId?: string | null | undefined;
};

/** @internal */
export const ListCardSchemeDefinitionsRequest$inboundSchema: z.ZodType<
  ListCardSchemeDefinitionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "x-gr4vy-merchant-account-id": z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "x-gr4vy-merchant-account-id": "xGr4vyMerchantAccountId",
  });
});

/** @internal */
export type ListCardSchemeDefinitionsRequest$Outbound = {
  "x-gr4vy-merchant-account-id"?: string | null | undefined;
};

/** @internal */
export const ListCardSchemeDefinitionsRequest$outboundSchema: z.ZodType<
  ListCardSchemeDefinitionsRequest$Outbound,
  z.ZodTypeDef,
  ListCardSchemeDefinitionsRequest
> = z.object({
  xGr4vyMerchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    xGr4vyMerchantAccountId: "x-gr4vy-merchant-account-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCardSchemeDefinitionsRequest$ {
  /** @deprecated use `ListCardSchemeDefinitionsRequest$inboundSchema` instead. */
  export const inboundSchema = ListCardSchemeDefinitionsRequest$inboundSchema;
  /** @deprecated use `ListCardSchemeDefinitionsRequest$outboundSchema` instead. */
  export const outboundSchema = ListCardSchemeDefinitionsRequest$outboundSchema;
  /** @deprecated use `ListCardSchemeDefinitionsRequest$Outbound` instead. */
  export type Outbound = ListCardSchemeDefinitionsRequest$Outbound;
}

export function listCardSchemeDefinitionsRequestToJSON(
  listCardSchemeDefinitionsRequest: ListCardSchemeDefinitionsRequest,
): string {
  return JSON.stringify(
    ListCardSchemeDefinitionsRequest$outboundSchema.parse(
      listCardSchemeDefinitionsRequest,
    ),
  );
}

export function listCardSchemeDefinitionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListCardSchemeDefinitionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCardSchemeDefinitionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCardSchemeDefinitionsRequest' from JSON`,
  );
}
