/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListGiftCardsRequest = {
  buyerExternalIdentifier?: string | null | undefined;
  buyerId?: string | null | undefined;
  cursor?: string | null | undefined;
  limit?: number | undefined;
  /**
   * The ID of the merchant account to use for this request.
   */
  xGr4vyMerchantAccountId?: string | null | undefined;
};

export type ListGiftCardsResponse = {
  result: components.CollectionGiftCard;
};

/** @internal */
export const ListGiftCardsRequest$inboundSchema: z.ZodType<
  ListGiftCardsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  buyer_external_identifier: z.nullable(z.string()).optional(),
  buyer_id: z.nullable(z.string()).optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  "x-gr4vy-merchant-account-id": z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "buyer_external_identifier": "buyerExternalIdentifier",
    "buyer_id": "buyerId",
    "x-gr4vy-merchant-account-id": "xGr4vyMerchantAccountId",
  });
});

/** @internal */
export type ListGiftCardsRequest$Outbound = {
  buyer_external_identifier?: string | null | undefined;
  buyer_id?: string | null | undefined;
  cursor?: string | null | undefined;
  limit: number;
  "x-gr4vy-merchant-account-id"?: string | null | undefined;
};

/** @internal */
export const ListGiftCardsRequest$outboundSchema: z.ZodType<
  ListGiftCardsRequest$Outbound,
  z.ZodTypeDef,
  ListGiftCardsRequest
> = z.object({
  buyerExternalIdentifier: z.nullable(z.string()).optional(),
  buyerId: z.nullable(z.string()).optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  xGr4vyMerchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    buyerExternalIdentifier: "buyer_external_identifier",
    buyerId: "buyer_id",
    xGr4vyMerchantAccountId: "x-gr4vy-merchant-account-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListGiftCardsRequest$ {
  /** @deprecated use `ListGiftCardsRequest$inboundSchema` instead. */
  export const inboundSchema = ListGiftCardsRequest$inboundSchema;
  /** @deprecated use `ListGiftCardsRequest$outboundSchema` instead. */
  export const outboundSchema = ListGiftCardsRequest$outboundSchema;
  /** @deprecated use `ListGiftCardsRequest$Outbound` instead. */
  export type Outbound = ListGiftCardsRequest$Outbound;
}

export function listGiftCardsRequestToJSON(
  listGiftCardsRequest: ListGiftCardsRequest,
): string {
  return JSON.stringify(
    ListGiftCardsRequest$outboundSchema.parse(listGiftCardsRequest),
  );
}

export function listGiftCardsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListGiftCardsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGiftCardsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGiftCardsRequest' from JSON`,
  );
}

/** @internal */
export const ListGiftCardsResponse$inboundSchema: z.ZodType<
  ListGiftCardsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.CollectionGiftCard$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListGiftCardsResponse$Outbound = {
  Result: components.CollectionGiftCard$Outbound;
};

/** @internal */
export const ListGiftCardsResponse$outboundSchema: z.ZodType<
  ListGiftCardsResponse$Outbound,
  z.ZodTypeDef,
  ListGiftCardsResponse
> = z.object({
  result: components.CollectionGiftCard$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListGiftCardsResponse$ {
  /** @deprecated use `ListGiftCardsResponse$inboundSchema` instead. */
  export const inboundSchema = ListGiftCardsResponse$inboundSchema;
  /** @deprecated use `ListGiftCardsResponse$outboundSchema` instead. */
  export const outboundSchema = ListGiftCardsResponse$outboundSchema;
  /** @deprecated use `ListGiftCardsResponse$Outbound` instead. */
  export type Outbound = ListGiftCardsResponse$Outbound;
}

export function listGiftCardsResponseToJSON(
  listGiftCardsResponse: ListGiftCardsResponse,
): string {
  return JSON.stringify(
    ListGiftCardsResponse$outboundSchema.parse(listGiftCardsResponse),
  );
}

export function listGiftCardsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListGiftCardsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListGiftCardsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListGiftCardsResponse' from JSON`,
  );
}
