/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListPaymentMethodNetworkTokensRequest = {
  /**
   * The ID of the payment method
   */
  paymentMethodId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  xGr4vyMerchantAccountId?: string | null | undefined;
};

/** @internal */
export const ListPaymentMethodNetworkTokensRequest$inboundSchema: z.ZodType<
  ListPaymentMethodNetworkTokensRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  payment_method_id: z.string(),
  "x-gr4vy-merchant-account-id": z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "payment_method_id": "paymentMethodId",
    "x-gr4vy-merchant-account-id": "xGr4vyMerchantAccountId",
  });
});

/** @internal */
export type ListPaymentMethodNetworkTokensRequest$Outbound = {
  payment_method_id: string;
  "x-gr4vy-merchant-account-id"?: string | null | undefined;
};

/** @internal */
export const ListPaymentMethodNetworkTokensRequest$outboundSchema: z.ZodType<
  ListPaymentMethodNetworkTokensRequest$Outbound,
  z.ZodTypeDef,
  ListPaymentMethodNetworkTokensRequest
> = z.object({
  paymentMethodId: z.string(),
  xGr4vyMerchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    paymentMethodId: "payment_method_id",
    xGr4vyMerchantAccountId: "x-gr4vy-merchant-account-id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListPaymentMethodNetworkTokensRequest$ {
  /** @deprecated use `ListPaymentMethodNetworkTokensRequest$inboundSchema` instead. */
  export const inboundSchema =
    ListPaymentMethodNetworkTokensRequest$inboundSchema;
  /** @deprecated use `ListPaymentMethodNetworkTokensRequest$outboundSchema` instead. */
  export const outboundSchema =
    ListPaymentMethodNetworkTokensRequest$outboundSchema;
  /** @deprecated use `ListPaymentMethodNetworkTokensRequest$Outbound` instead. */
  export type Outbound = ListPaymentMethodNetworkTokensRequest$Outbound;
}

export function listPaymentMethodNetworkTokensRequestToJSON(
  listPaymentMethodNetworkTokensRequest: ListPaymentMethodNetworkTokensRequest,
): string {
  return JSON.stringify(
    ListPaymentMethodNetworkTokensRequest$outboundSchema.parse(
      listPaymentMethodNetworkTokensRequest,
    ),
  );
}

export function listPaymentMethodNetworkTokensRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListPaymentMethodNetworkTokensRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListPaymentMethodNetworkTokensRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPaymentMethodNetworkTokensRequest' from JSON`,
  );
}
