/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type ListRolesRequest = {
    /**
     * Defines the maximum number of items to return for this request.
     */
    limit?: number | undefined;
    /**
     * A cursor that identifies the page of results to return. This is used to
     *
     * @remarks
     * paginate the results of this API.
     *
     * For the first page of results, this parameter can be left out.
     * For additional pages, use the value returned by the API in
     * the `next_cursor` field. Similarly the `previous_cursor` can be used to
     * reverse backwards in the list.
     */
    cursor?: string | undefined;
};

export type ListRolesResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Returns a list of roles.
     */
    roles?: components.Roles | undefined;
};

/** @internal */
export namespace ListRolesRequest$ {
    export type Inbound = {
        limit?: number | undefined;
        cursor?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ListRolesRequest, z.ZodTypeDef, Inbound> = z
        .object({
            limit: z.number().int().default(20),
            cursor: z.string().optional(),
        })
        .transform((v) => {
            return {
                limit: v.limit,
                ...(v.cursor === undefined ? null : { cursor: v.cursor }),
            };
        });

    export type Outbound = {
        limit: number;
        cursor?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListRolesRequest> = z
        .object({
            limit: z.number().int().default(20),
            cursor: z.string().optional(),
        })
        .transform((v) => {
            return {
                limit: v.limit,
                ...(v.cursor === undefined ? null : { cursor: v.cursor }),
            };
        });
}

/** @internal */
export namespace ListRolesResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Roles?: components.Roles$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<ListRolesResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Roles: components.Roles$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Roles === undefined ? null : { roles: v.Roles }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Roles?: components.Roles$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListRolesResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            roles: components.Roles$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.roles === undefined ? null : { Roles: v.roles }),
            };
        });
}
