/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type RefundAllTransactionMethodsRequest = {
    transactionId: string;
    transactionRefundAllCreate?: components.TransactionRefundAllCreate | undefined;
};

/** @internal */
export const RefundAllTransactionMethodsRequest$inboundSchema: z.ZodType<
    RefundAllTransactionMethodsRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        transaction_id: z.string(),
        TransactionRefundAllCreate: components.TransactionRefundAllCreate$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            transaction_id: "transactionId",
            TransactionRefundAllCreate: "transactionRefundAllCreate",
        });
    });

/** @internal */
export type RefundAllTransactionMethodsRequest$Outbound = {
    transaction_id: string;
    TransactionRefundAllCreate?: components.TransactionRefundAllCreate$Outbound | undefined;
};

/** @internal */
export const RefundAllTransactionMethodsRequest$outboundSchema: z.ZodType<
    RefundAllTransactionMethodsRequest$Outbound,
    z.ZodTypeDef,
    RefundAllTransactionMethodsRequest
> = z
    .object({
        transactionId: z.string(),
        transactionRefundAllCreate: components.TransactionRefundAllCreate$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            transactionId: "transaction_id",
            transactionRefundAllCreate: "TransactionRefundAllCreate",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RefundAllTransactionMethodsRequest$ {
    /** @deprecated use `RefundAllTransactionMethodsRequest$inboundSchema` instead. */
    export const inboundSchema = RefundAllTransactionMethodsRequest$inboundSchema;
    /** @deprecated use `RefundAllTransactionMethodsRequest$outboundSchema` instead. */
    export const outboundSchema = RefundAllTransactionMethodsRequest$outboundSchema;
    /** @deprecated use `RefundAllTransactionMethodsRequest$Outbound` instead. */
    export type Outbound = RefundAllTransactionMethodsRequest$Outbound;
}
