/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type UpdateCheckoutSessionRequest = {
    sessionId: string;
    checkoutSessionUpdate: components.CheckoutSessionUpdate;
};

/** @internal */
export const UpdateCheckoutSessionRequest$inboundSchema: z.ZodType<
    UpdateCheckoutSessionRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        session_id: z.string(),
        CheckoutSessionUpdate: components.CheckoutSessionUpdate$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            session_id: "sessionId",
            CheckoutSessionUpdate: "checkoutSessionUpdate",
        });
    });

/** @internal */
export type UpdateCheckoutSessionRequest$Outbound = {
    session_id: string;
    CheckoutSessionUpdate: components.CheckoutSessionUpdate$Outbound;
};

/** @internal */
export const UpdateCheckoutSessionRequest$outboundSchema: z.ZodType<
    UpdateCheckoutSessionRequest$Outbound,
    z.ZodTypeDef,
    UpdateCheckoutSessionRequest
> = z
    .object({
        sessionId: z.string(),
        checkoutSessionUpdate: components.CheckoutSessionUpdate$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            sessionId: "session_id",
            checkoutSessionUpdate: "CheckoutSessionUpdate",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateCheckoutSessionRequest$ {
    /** @deprecated use `UpdateCheckoutSessionRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateCheckoutSessionRequest$inboundSchema;
    /** @deprecated use `UpdateCheckoutSessionRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateCheckoutSessionRequest$outboundSchema;
    /** @deprecated use `UpdateCheckoutSessionRequest$Outbound` instead. */
    export type Outbound = UpdateCheckoutSessionRequest$Outbound;
}
