/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type UpdateMerchantAccountRequest = {
    /**
     * The unique ID for a merchant account.
     */
    merchantAccountId: string;
    merchantAccountUpdate?: components.MerchantAccountUpdate | undefined;
};

/** @internal */
export const UpdateMerchantAccountRequest$inboundSchema: z.ZodType<
    UpdateMerchantAccountRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        merchant_account_id: z.string(),
        MerchantAccountUpdate: components.MerchantAccountUpdate$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            merchant_account_id: "merchantAccountId",
            MerchantAccountUpdate: "merchantAccountUpdate",
        });
    });

/** @internal */
export type UpdateMerchantAccountRequest$Outbound = {
    merchant_account_id: string;
    MerchantAccountUpdate?: components.MerchantAccountUpdate$Outbound | undefined;
};

/** @internal */
export const UpdateMerchantAccountRequest$outboundSchema: z.ZodType<
    UpdateMerchantAccountRequest$Outbound,
    z.ZodTypeDef,
    UpdateMerchantAccountRequest
> = z
    .object({
        merchantAccountId: z.string(),
        merchantAccountUpdate: components.MerchantAccountUpdate$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            merchantAccountId: "merchant_account_id",
            merchantAccountUpdate: "MerchantAccountUpdate",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateMerchantAccountRequest$ {
    /** @deprecated use `UpdateMerchantAccountRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateMerchantAccountRequest$inboundSchema;
    /** @deprecated use `UpdateMerchantAccountRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateMerchantAccountRequest$outboundSchema;
    /** @deprecated use `UpdateMerchantAccountRequest$Outbound` instead. */
    export type Outbound = UpdateMerchantAccountRequest$Outbound;
}
