/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as components from "../components/index.js";
import * as z from "zod";

/**
 * The name of the Flow.
 */
export const UpdateFlowRulePathParamFlow = {
    Checkout: "checkout",
    CardTransaction: "card-transaction",
    NonCardTransaction: "non-card-transaction",
    RedirectTransaction: "redirect-transaction",
} as const;
/**
 * The name of the Flow.
 */
export type UpdateFlowRulePathParamFlow = ClosedEnum<typeof UpdateFlowRulePathParamFlow>;

/**
 * Action for the given rule. Actions can only be used in
 *
 * @remarks
 * flows that support them.
 *
 * * The `checkout` flow only supports the
 * `select-payment-options` action.
 * * The `card-transaction` supports the `route-transaction`,
 * `skip-3ds`, and `decline-early` actions.
 * * The `non-card-transaction` flow only supports the
 * `decline-early` action.
 * * The `redirect-transaction` flow only supports
 * the `route-transaction` action.
 *
 */
export const UpdateFlowRulePathParamAction = {
    SelectPaymentOptions: "select-payment-options",
    DeclineEarly: "decline-early",
    RouteTransaction: "route-transaction",
    Skip3ds: "skip-3ds",
} as const;
/**
 * Action for the given rule. Actions can only be used in
 *
 * @remarks
 * flows that support them.
 *
 * * The `checkout` flow only supports the
 * `select-payment-options` action.
 * * The `card-transaction` supports the `route-transaction`,
 * `skip-3ds`, and `decline-early` actions.
 * * The `non-card-transaction` flow only supports the
 * `decline-early` action.
 * * The `redirect-transaction` flow only supports
 * the `route-transaction` action.
 *
 */
export type UpdateFlowRulePathParamAction = ClosedEnum<typeof UpdateFlowRulePathParamAction>;

export type UpdateFlowRuleRequest = {
    /**
     * The flow name. This can be one of the following.
     *
     * @remarks
     *
     * - `checkout` - Applies during checkout to determine what payment options are shown.
     * - `card-transaction` - Applies when processing a card transaction.
     * - `non-card-transaction` - Applies when processing a gift card only transaction, or a
     * redirect transaction using the `decline-early` action.
     * - `redirect-transaction` - Applies when processing any other transaction.
     */
    flow: UpdateFlowRulePathParamFlow;
    /**
     * The flow action.
     */
    action: UpdateFlowRulePathParamAction;
    /**
     * The unique ID for a rule.
     */
    ruleId: string;
    flowRuleUpdateRequest?: components.FlowRuleUpdateRequest | undefined;
};

/** @internal */
export const UpdateFlowRulePathParamFlow$inboundSchema: z.ZodNativeEnum<
    typeof UpdateFlowRulePathParamFlow
> = z.nativeEnum(UpdateFlowRulePathParamFlow);

/** @internal */
export const UpdateFlowRulePathParamFlow$outboundSchema: z.ZodNativeEnum<
    typeof UpdateFlowRulePathParamFlow
> = UpdateFlowRulePathParamFlow$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateFlowRulePathParamFlow$ {
    /** @deprecated use `UpdateFlowRulePathParamFlow$inboundSchema` instead. */
    export const inboundSchema = UpdateFlowRulePathParamFlow$inboundSchema;
    /** @deprecated use `UpdateFlowRulePathParamFlow$outboundSchema` instead. */
    export const outboundSchema = UpdateFlowRulePathParamFlow$outboundSchema;
}

/** @internal */
export const UpdateFlowRulePathParamAction$inboundSchema: z.ZodNativeEnum<
    typeof UpdateFlowRulePathParamAction
> = z.nativeEnum(UpdateFlowRulePathParamAction);

/** @internal */
export const UpdateFlowRulePathParamAction$outboundSchema: z.ZodNativeEnum<
    typeof UpdateFlowRulePathParamAction
> = UpdateFlowRulePathParamAction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateFlowRulePathParamAction$ {
    /** @deprecated use `UpdateFlowRulePathParamAction$inboundSchema` instead. */
    export const inboundSchema = UpdateFlowRulePathParamAction$inboundSchema;
    /** @deprecated use `UpdateFlowRulePathParamAction$outboundSchema` instead. */
    export const outboundSchema = UpdateFlowRulePathParamAction$outboundSchema;
}

/** @internal */
export const UpdateFlowRuleRequest$inboundSchema: z.ZodType<
    UpdateFlowRuleRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        flow: UpdateFlowRulePathParamFlow$inboundSchema,
        action: UpdateFlowRulePathParamAction$inboundSchema,
        rule_id: z.string(),
        FlowRuleUpdateRequest: components.FlowRuleUpdateRequest$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            rule_id: "ruleId",
            FlowRuleUpdateRequest: "flowRuleUpdateRequest",
        });
    });

/** @internal */
export type UpdateFlowRuleRequest$Outbound = {
    flow: string;
    action: string;
    rule_id: string;
    FlowRuleUpdateRequest?: components.FlowRuleUpdateRequest$Outbound | undefined;
};

/** @internal */
export const UpdateFlowRuleRequest$outboundSchema: z.ZodType<
    UpdateFlowRuleRequest$Outbound,
    z.ZodTypeDef,
    UpdateFlowRuleRequest
> = z
    .object({
        flow: UpdateFlowRulePathParamFlow$outboundSchema,
        action: UpdateFlowRulePathParamAction$outboundSchema,
        ruleId: z.string(),
        flowRuleUpdateRequest: components.FlowRuleUpdateRequest$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            ruleId: "rule_id",
            flowRuleUpdateRequest: "FlowRuleUpdateRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateFlowRuleRequest$ {
    /** @deprecated use `UpdateFlowRuleRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateFlowRuleRequest$inboundSchema;
    /** @deprecated use `UpdateFlowRuleRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateFlowRuleRequest$outboundSchema;
    /** @deprecated use `UpdateFlowRuleRequest$Outbound` instead. */
    export type Outbound = UpdateFlowRuleRequest$Outbound;
}
