/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

/**
 * Base model with JSON encoders.
 */
export type AccountUpdaterJobCreate = {
    paymentMethodIds: Array<string>;
};

/** @internal */
export const AccountUpdaterJobCreate$inboundSchema: z.ZodType<
    AccountUpdaterJobCreate,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        payment_method_ids: z.array(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            payment_method_ids: "paymentMethodIds",
        });
    });

/** @internal */
export type AccountUpdaterJobCreate$Outbound = {
    payment_method_ids: Array<string>;
};

/** @internal */
export const AccountUpdaterJobCreate$outboundSchema: z.ZodType<
    AccountUpdaterJobCreate$Outbound,
    z.ZodTypeDef,
    AccountUpdaterJobCreate
> = z
    .object({
        paymentMethodIds: z.array(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            paymentMethodIds: "payment_method_ids",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountUpdaterJobCreate$ {
    /** @deprecated use `AccountUpdaterJobCreate$inboundSchema` instead. */
    export const inboundSchema = AccountUpdaterJobCreate$inboundSchema;
    /** @deprecated use `AccountUpdaterJobCreate$outboundSchema` instead. */
    export const outboundSchema = AccountUpdaterJobCreate$outboundSchema;
    /** @deprecated use `AccountUpdaterJobCreate$Outbound` instead. */
    export type Outbound = AccountUpdaterJobCreate$Outbound;
}
