/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    ApiRoutersPaymentServicesSchemasField,
    ApiRoutersPaymentServicesSchemasField$inboundSchema,
    ApiRoutersPaymentServicesSchemasField$Outbound,
    ApiRoutersPaymentServicesSchemasField$outboundSchema,
} from "./apirouterspaymentservicesschemasfield.js";
import * as z from "zod";

/**
 * Base model with JSON encoders.
 */
export type ApiRoutersPaymentServicesSchemasVerifyCredentials = {
    paymentServiceDefinitionId: string;
    paymentServiceId?: string | undefined;
    fields: Array<ApiRoutersPaymentServicesSchemasField>;
};

/** @internal */
export const ApiRoutersPaymentServicesSchemasVerifyCredentials$inboundSchema: z.ZodType<
    ApiRoutersPaymentServicesSchemasVerifyCredentials,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        payment_service_definition_id: z.string(),
        payment_service_id: z.string().optional(),
        fields: z.array(ApiRoutersPaymentServicesSchemasField$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            payment_service_definition_id: "paymentServiceDefinitionId",
            payment_service_id: "paymentServiceId",
        });
    });

/** @internal */
export type ApiRoutersPaymentServicesSchemasVerifyCredentials$Outbound = {
    payment_service_definition_id: string;
    payment_service_id?: string | undefined;
    fields: Array<ApiRoutersPaymentServicesSchemasField$Outbound>;
};

/** @internal */
export const ApiRoutersPaymentServicesSchemasVerifyCredentials$outboundSchema: z.ZodType<
    ApiRoutersPaymentServicesSchemasVerifyCredentials$Outbound,
    z.ZodTypeDef,
    ApiRoutersPaymentServicesSchemasVerifyCredentials
> = z
    .object({
        paymentServiceDefinitionId: z.string(),
        paymentServiceId: z.string().optional(),
        fields: z.array(ApiRoutersPaymentServicesSchemasField$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            paymentServiceDefinitionId: "payment_service_definition_id",
            paymentServiceId: "payment_service_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiRoutersPaymentServicesSchemasVerifyCredentials$ {
    /** @deprecated use `ApiRoutersPaymentServicesSchemasVerifyCredentials$inboundSchema` instead. */
    export const inboundSchema = ApiRoutersPaymentServicesSchemasVerifyCredentials$inboundSchema;
    /** @deprecated use `ApiRoutersPaymentServicesSchemasVerifyCredentials$outboundSchema` instead. */
    export const outboundSchema = ApiRoutersPaymentServicesSchemasVerifyCredentials$outboundSchema;
    /** @deprecated use `ApiRoutersPaymentServicesSchemasVerifyCredentials$Outbound` instead. */
    export type Outbound = ApiRoutersPaymentServicesSchemasVerifyCredentials$Outbound;
}
