/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AuditLogEntry,
  AuditLogEntry$inboundSchema,
  AuditLogEntry$Outbound,
  AuditLogEntry$outboundSchema,
} from "./auditlogentry.js";

export type AuditLogEntries = {
  /**
   * A list of items returned for this request.
   */
  items: Array<AuditLogEntry>;
  /**
   * The number of items for this page.
   */
  limit?: number | undefined;
  /**
   * The cursor pointing at the next page of items.
   */
  nextCursor?: string | null | undefined;
  /**
   * The cursor pointing at the previous page of items.
   */
  previousCursor?: string | null | undefined;
};

/** @internal */
export const AuditLogEntries$inboundSchema: z.ZodType<
  AuditLogEntries,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(AuditLogEntry$inboundSchema),
  limit: z.number().int().default(20),
  next_cursor: z.nullable(z.string()).optional(),
  previous_cursor: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "next_cursor": "nextCursor",
    "previous_cursor": "previousCursor",
  });
});

/** @internal */
export type AuditLogEntries$Outbound = {
  items: Array<AuditLogEntry$Outbound>;
  limit: number;
  next_cursor?: string | null | undefined;
  previous_cursor?: string | null | undefined;
};

/** @internal */
export const AuditLogEntries$outboundSchema: z.ZodType<
  AuditLogEntries$Outbound,
  z.ZodTypeDef,
  AuditLogEntries
> = z.object({
  items: z.array(AuditLogEntry$outboundSchema),
  limit: z.number().int().default(20),
  nextCursor: z.nullable(z.string()).optional(),
  previousCursor: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    nextCursor: "next_cursor",
    previousCursor: "previous_cursor",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuditLogEntries$ {
  /** @deprecated use `AuditLogEntries$inboundSchema` instead. */
  export const inboundSchema = AuditLogEntries$inboundSchema;
  /** @deprecated use `AuditLogEntries$outboundSchema` instead. */
  export const outboundSchema = AuditLogEntries$outboundSchema;
  /** @deprecated use `AuditLogEntries$Outbound` instead. */
  export type Outbound = AuditLogEntries$Outbound;
}

export function auditLogEntriesToJSON(
  auditLogEntries: AuditLogEntries,
): string {
  return JSON.stringify(AuditLogEntries$outboundSchema.parse(auditLogEntries));
}

export function auditLogEntriesFromJSON(
  jsonString: string,
): SafeParseResult<AuditLogEntries, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AuditLogEntries$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AuditLogEntries' from JSON`,
  );
}
