/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CardSchemeDefinition,
  CardSchemeDefinition$inboundSchema,
  CardSchemeDefinition$Outbound,
  CardSchemeDefinition$outboundSchema,
} from "./cardschemedefinition.js";

export type CardSchemeDefinitions = {
  /**
   * A list of items returned for this request.
   */
  items: Array<CardSchemeDefinition>;
};

/** @internal */
export const CardSchemeDefinitions$inboundSchema: z.ZodType<
  CardSchemeDefinitions,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(CardSchemeDefinition$inboundSchema),
});

/** @internal */
export type CardSchemeDefinitions$Outbound = {
  items: Array<CardSchemeDefinition$Outbound>;
};

/** @internal */
export const CardSchemeDefinitions$outboundSchema: z.ZodType<
  CardSchemeDefinitions$Outbound,
  z.ZodTypeDef,
  CardSchemeDefinitions
> = z.object({
  items: z.array(CardSchemeDefinition$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CardSchemeDefinitions$ {
  /** @deprecated use `CardSchemeDefinitions$inboundSchema` instead. */
  export const inboundSchema = CardSchemeDefinitions$inboundSchema;
  /** @deprecated use `CardSchemeDefinitions$outboundSchema` instead. */
  export const outboundSchema = CardSchemeDefinitions$outboundSchema;
  /** @deprecated use `CardSchemeDefinitions$Outbound` instead. */
  export type Outbound = CardSchemeDefinitions$Outbound;
}

export function cardSchemeDefinitionsToJSON(
  cardSchemeDefinitions: CardSchemeDefinitions,
): string {
  return JSON.stringify(
    CardSchemeDefinitions$outboundSchema.parse(cardSchemeDefinitions),
  );
}

export function cardSchemeDefinitionsFromJSON(
  jsonString: string,
): SafeParseResult<CardSchemeDefinitions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardSchemeDefinitions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardSchemeDefinitions' from JSON`,
  );
}
