/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Connection, Connection$ } from "./connection";
import * as z from "zod";

/**
 * A list of configured connections.
 */
export type Connections = {
    items?: Array<Connection> | undefined;
};

/** @internal */
export namespace Connections$ {
    export type Inbound = {
        items?: Array<Connection$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<Connections, z.ZodTypeDef, Inbound> = z
        .object({
            items: z.array(Connection$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.items === undefined ? null : { items: v.items }),
            };
        });

    export type Outbound = {
        items?: Array<Connection$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Connections> = z
        .object({
            items: z.array(Connection$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.items === undefined ? null : { items: v.items }),
            };
        });
}
