/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

/**
 * Domain name for a digital wallet.
 */
export type DigitalWalletDomain = {
    /**
     * The domain name that a digital wallet can be used on. To use a
     *
     * @remarks
     * digital wallet on a website, the domain of the site is required to be
     * in this list.
     */
    domainName: string;
};

/** @internal */
export const DigitalWalletDomain$inboundSchema: z.ZodType<
    DigitalWalletDomain,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        domain_name: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            domain_name: "domainName",
        });
    });

/** @internal */
export type DigitalWalletDomain$Outbound = {
    domain_name: string;
};

/** @internal */
export const DigitalWalletDomain$outboundSchema: z.ZodType<
    DigitalWalletDomain$Outbound,
    z.ZodTypeDef,
    DigitalWalletDomain
> = z
    .object({
        domainName: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            domainName: "domain_name",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DigitalWalletDomain$ {
    /** @deprecated use `DigitalWalletDomain$inboundSchema` instead. */
    export const inboundSchema = DigitalWalletDomain$inboundSchema;
    /** @deprecated use `DigitalWalletDomain$outboundSchema` instead. */
    export const outboundSchema = DigitalWalletDomain$outboundSchema;
    /** @deprecated use `DigitalWalletDomain$Outbound` instead. */
    export type Outbound = DigitalWalletDomain$Outbound;
}
