/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    DigitalWallet,
    DigitalWallet$inboundSchema,
    DigitalWallet$Outbound,
    DigitalWallet$outboundSchema,
} from "./digitalwallet.js";
import * as z from "zod";

/**
 * A list of registered digital wallets.
 */
export type DigitalWallets = {
    /**
     * A list of registered digital wallets.
     */
    items?: Array<DigitalWallet> | undefined;
};

/** @internal */
export const DigitalWallets$inboundSchema: z.ZodType<DigitalWallets, z.ZodTypeDef, unknown> =
    z.object({
        items: z.array(DigitalWallet$inboundSchema).optional(),
    });

/** @internal */
export type DigitalWallets$Outbound = {
    items?: Array<DigitalWallet$Outbound> | undefined;
};

/** @internal */
export const DigitalWallets$outboundSchema: z.ZodType<
    DigitalWallets$Outbound,
    z.ZodTypeDef,
    DigitalWallets
> = z.object({
    items: z.array(DigitalWallet$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DigitalWallets$ {
    /** @deprecated use `DigitalWallets$inboundSchema` instead. */
    export const inboundSchema = DigitalWallets$inboundSchema;
    /** @deprecated use `DigitalWallets$outboundSchema` instead. */
    export const outboundSchema = DigitalWallets$outboundSchema;
    /** @deprecated use `DigitalWallets$Outbound` instead. */
    export type Outbound = DigitalWallets$Outbound;
}
