/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of match made for this rule.
 */
export enum FlowPaymentMethodsConditionName {
    PaymentMethod = "payment_method",
}

/**
 * The comparison to make on the `value`.
 */
export enum FlowPaymentMethodsConditionOperator {
    IsOneOf = "is_one_of",
    IsNotOneOf = "is_not_one_of",
}

export enum FlowPaymentMethodsConditionValue {
    Afterpay = "afterpay",
    Alipay = "alipay",
    Alipayhk = "alipayhk",
    Applepay = "applepay",
    Bacs = "bacs",
    Banked = "banked",
    Becs = "becs",
    Bitpay = "bitpay",
    Boleto = "boleto",
    Boost = "boost",
    Card = "card",
    Cashapp = "cashapp",
    Chaseorbital = "chaseorbital",
    Clearpay = "clearpay",
    ClickToPay = "click-to-pay",
    Dana = "dana",
    Dcb = "dcb",
    Dlocal = "dlocal",
    Ebanx = "ebanx",
    Gcash = "gcash",
    Giropay = "giropay",
    Gocardless = "gocardless",
    Googlepay = "googlepay",
    Gopay = "gopay",
    Grabpay = "grabpay",
    Ideal = "ideal",
    Kakaopay = "kakaopay",
    Klarna = "klarna",
    Laybuy = "laybuy",
    Linkaja = "linkaja",
    Maybankqrpay = "maybankqrpay",
    Multibanco = "multibanco",
    Oney3x = "oney_3x",
    Oney4x = "oney_4x",
    Oney6x = "oney_6x",
    Oney10x = "oney_10x",
    Oney12x = "oney_12x",
    Ovo = "ovo",
    Oxxo = "oxxo",
    Payid = "payid",
    Paymaya = "paymaya",
    Paypal = "paypal",
    Paypalpaylater = "paypalpaylater",
    Payto = "payto",
    Venmo = "venmo",
    Pix = "pix",
    Rabbitlinepay = "rabbitlinepay",
    Scalapay = "scalapay",
    Sepa = "sepa",
    Shopeepay = "shopeepay",
    Singteldash = "singteldash",
    Sofort = "sofort",
    Stripedd = "stripedd",
    Thaiqr = "thaiqr",
    Touchngo = "touchngo",
    Truemoney = "truemoney",
    Trustly = "trustly",
    Trustlyeurope = "trustlyeurope",
    Givingblock = "givingblock",
    Wechat = "wechat",
    Zippay = "zippay",
    Bancontact = "bancontact",
    Eps = "eps",
    Linepay = "linepay",
    Razorpay = "razorpay",
    Multipago = "multipago",
    Waave = "waave",
    Smartpay = "smartpay",
    Vipps = "vipps",
}

/**
 * Payment methods condition with a name, operator, and value. This
 *
 * @remarks
 * condition is only for use with the `decline-early` action.
 */
export type FlowPaymentMethodsCondition = {
    /**
     * The type of match made for this rule.
     */
    name: FlowPaymentMethodsConditionName;
    /**
     * The comparison to make on the `value`.
     */
    operator: FlowPaymentMethodsConditionOperator;
    /**
     * Payment method(s) to compare the transaction to.
     */
    value: Array<FlowPaymentMethodsConditionValue>;
};

/** @internal */
export const FlowPaymentMethodsConditionName$ = z.nativeEnum(FlowPaymentMethodsConditionName);

/** @internal */
export const FlowPaymentMethodsConditionOperator$ = z.nativeEnum(
    FlowPaymentMethodsConditionOperator
);

/** @internal */
export const FlowPaymentMethodsConditionValue$ = z.nativeEnum(FlowPaymentMethodsConditionValue);

/** @internal */
export namespace FlowPaymentMethodsCondition$ {
    export type Inbound = {
        name: FlowPaymentMethodsConditionName;
        operator: FlowPaymentMethodsConditionOperator;
        value: Array<FlowPaymentMethodsConditionValue>;
    };

    export const inboundSchema: z.ZodType<FlowPaymentMethodsCondition, z.ZodTypeDef, Inbound> = z
        .object({
            name: FlowPaymentMethodsConditionName$,
            operator: FlowPaymentMethodsConditionOperator$,
            value: z.array(FlowPaymentMethodsConditionValue$),
        })
        .transform((v) => {
            return {
                name: v.name,
                operator: v.operator,
                value: v.value,
            };
        });

    export type Outbound = {
        name: FlowPaymentMethodsConditionName;
        operator: FlowPaymentMethodsConditionOperator;
        value: Array<FlowPaymentMethodsConditionValue>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FlowPaymentMethodsCondition> = z
        .object({
            name: FlowPaymentMethodsConditionName$,
            operator: FlowPaymentMethodsConditionOperator$,
            value: z.array(FlowPaymentMethodsConditionValue$),
        })
        .transform((v) => {
            return {
                name: v.name,
                operator: v.operator,
                value: v.value,
            };
        });
}
