/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of match made for this rule.
 */
export enum FlowAmountConditionName {
    Amount = "amount",
}

/**
 * The comparison to make on the currency code `value`.
 */
export enum Operator {
    LessThan = "less_than",
    GreaterThan = "greater_than",
}

/**
 * Amount value compare the transaction to.
 */
export type Value = {
    /**
     * Currency ISO codes to compare the transaction to.
     */
    currency?: string | undefined;
    /**
     * Amount value to compare transaction value to.
     */
    value?: number | undefined;
};

/**
 * Amount conditions with a name, operator, and value.
 */
export type FlowAmountCondition = {
    /**
     * The type of match made for this rule.
     */
    name: FlowAmountConditionName;
    /**
     * The comparison to make on the currency code `value`.
     */
    operator: Operator;
    /**
     * Amount value compare the transaction to.
     */
    value: Value;
};

/** @internal */
export const FlowAmountConditionName$ = z.nativeEnum(FlowAmountConditionName);

/** @internal */
export const Operator$ = z.nativeEnum(Operator);

/** @internal */
export namespace Value$ {
    export type Inbound = {
        currency?: string | undefined;
        value?: number | undefined;
    };

    export const inboundSchema: z.ZodType<Value, z.ZodTypeDef, Inbound> = z
        .object({
            currency: z.string().optional(),
            value: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.currency === undefined ? null : { currency: v.currency }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });

    export type Outbound = {
        currency?: string | undefined;
        value?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Value> = z
        .object({
            currency: z.string().optional(),
            value: z.number().optional(),
        })
        .transform((v) => {
            return {
                ...(v.currency === undefined ? null : { currency: v.currency }),
                ...(v.value === undefined ? null : { value: v.value }),
            };
        });
}

/** @internal */
export namespace FlowAmountCondition$ {
    export type Inbound = {
        name: FlowAmountConditionName;
        operator: Operator;
        value: Value$.Inbound;
    };

    export const inboundSchema: z.ZodType<FlowAmountCondition, z.ZodTypeDef, Inbound> = z
        .object({
            name: FlowAmountConditionName$,
            operator: Operator$,
            value: z.lazy(() => Value$.inboundSchema),
        })
        .transform((v) => {
            return {
                name: v.name,
                operator: v.operator,
                value: v.value,
            };
        });

    export type Outbound = {
        name: FlowAmountConditionName;
        operator: Operator;
        value: Value$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FlowAmountCondition> = z
        .object({
            name: FlowAmountConditionName$,
            operator: Operator$,
            value: z.lazy(() => Value$.outboundSchema),
        })
        .transform((v) => {
            return {
                name: v.name,
                operator: v.operator,
                value: v.value,
            };
        });
}
