/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../../types/enums.js";

export const NetworkTokenStatus = {
  Active: "active",
  Inactive: "inactive",
  Suspended: "suspended",
  Deleted: "deleted",
} as const;
export type NetworkTokenStatus = OpenEnum<typeof NetworkTokenStatus>;

/** @internal */
export const NetworkTokenStatus$inboundSchema: z.ZodType<
  NetworkTokenStatus,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(NetworkTokenStatus),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const NetworkTokenStatus$outboundSchema: z.ZodType<
  NetworkTokenStatus,
  z.ZodTypeDef,
  NetworkTokenStatus
> = z.union([
  z.nativeEnum(NetworkTokenStatus),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NetworkTokenStatus$ {
  /** @deprecated use `NetworkTokenStatus$inboundSchema` instead. */
  export const inboundSchema = NetworkTokenStatus$inboundSchema;
  /** @deprecated use `NetworkTokenStatus$outboundSchema` instead. */
  export const outboundSchema = NetworkTokenStatus$outboundSchema;
}
