/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const PayoutCategory = {
  OnlineGambling: "online_gambling",
} as const;
export type PayoutCategory = ClosedEnum<typeof PayoutCategory>;

/** @internal */
export const PayoutCategory$inboundSchema: z.ZodNativeEnum<
  typeof PayoutCategory
> = z.nativeEnum(PayoutCategory);

/** @internal */
export const PayoutCategory$outboundSchema: z.ZodNativeEnum<
  typeof PayoutCategory
> = PayoutCategory$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PayoutCategory$ {
  /** @deprecated use `PayoutCategory$inboundSchema` instead. */
  export const inboundSchema = PayoutCategory$inboundSchema;
  /** @deprecated use `PayoutCategory$outboundSchema` instead. */
  export const outboundSchema = PayoutCategory$outboundSchema;
}
