/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ShippingDetail, ShippingDetail$ } from "./shippingdetail";
import * as z from "zod";

/**
 * A list of shipping details.
 */
export type ShippingDetails = {
    /**
     * A list of shipping details.
     */
    items?: Array<ShippingDetail> | undefined;
};

/** @internal */
export namespace ShippingDetails$ {
    export type Inbound = {
        items?: Array<ShippingDetail$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<ShippingDetails, z.ZodTypeDef, Inbound> = z
        .object({
            items: z.array(ShippingDetail$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.items === undefined ? null : { items: v.items }),
            };
        });

    export type Outbound = {
        items?: Array<ShippingDetail$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ShippingDetails> = z
        .object({
            items: z.array(ShippingDetail$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.items === undefined ? null : { items: v.items }),
            };
        });
}
