/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ThreeDSecureStatus = {
  SetupError: "setup_error",
  Error: "error",
  Declined: "declined",
  Cancelled: "cancelled",
  Complete: "complete",
} as const;
export type ThreeDSecureStatus = ClosedEnum<typeof ThreeDSecureStatus>;

/** @internal */
export const ThreeDSecureStatus$inboundSchema: z.ZodNativeEnum<
  typeof ThreeDSecureStatus
> = z.nativeEnum(ThreeDSecureStatus);

/** @internal */
export const ThreeDSecureStatus$outboundSchema: z.ZodNativeEnum<
  typeof ThreeDSecureStatus
> = ThreeDSecureStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ThreeDSecureStatus$ {
  /** @deprecated use `ThreeDSecureStatus$inboundSchema` instead. */
  export const inboundSchema = ThreeDSecureStatus$inboundSchema;
  /** @deprecated use `ThreeDSecureStatus$outboundSchema` instead. */
  export const outboundSchema = ThreeDSecureStatus$outboundSchema;
}
