/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../../types/enums.js";

export const ThreeDSecureMethod = {
  Challenge: "challenge",
  Frictionless: "frictionless",
} as const;
export type ThreeDSecureMethod = OpenEnum<typeof ThreeDSecureMethod>;

/** @internal */
export const ThreeDSecureMethod$inboundSchema: z.ZodType<
  ThreeDSecureMethod,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(ThreeDSecureMethod),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const ThreeDSecureMethod$outboundSchema: z.ZodType<
  ThreeDSecureMethod,
  z.ZodTypeDef,
  ThreeDSecureMethod
> = z.union([
  z.nativeEnum(ThreeDSecureMethod),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ThreeDSecureMethod$ {
  /** @deprecated use `ThreeDSecureMethod$inboundSchema` instead. */
  export const inboundSchema = ThreeDSecureMethod$inboundSchema;
  /** @deprecated use `ThreeDSecureMethod$outboundSchema` instead. */
  export const outboundSchema = ThreeDSecureMethod$outboundSchema;
}
