/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../../types/enums.js";

export const VoidStatus = {
  Succeeded: "succeeded",
  Pending: "pending",
  Declined: "declined",
  Failed: "failed",
} as const;
export type VoidStatus = OpenEnum<typeof VoidStatus>;

/** @internal */
export const VoidStatus$inboundSchema: z.ZodType<
  VoidStatus,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(VoidStatus),
    z.string().transform(catchUnrecognizedEnum),
  ]);

/** @internal */
export const VoidStatus$outboundSchema: z.ZodType<
  VoidStatus,
  z.ZodTypeDef,
  VoidStatus
> = z.union([
  z.nativeEnum(VoidStatus),
  z.string().and(z.custom<Unrecognized<string>>()),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VoidStatus$ {
  /** @deprecated use `VoidStatus$inboundSchema` instead. */
  export const inboundSchema = VoidStatus$inboundSchema;
  /** @deprecated use `VoidStatus$outboundSchema` instead. */
  export const outboundSchema = VoidStatus$outboundSchema;
}
